#!/bin/bash

pkg_mgr() {
  # set bin path
  bin='/usr/bin'
  [[ -d $bin ]] || {
    bin='C:/Program Files'
    [[ -d $bin ]] || bin='/data/data/com.termux/files/usr/bin'
  }

  # set package manager by *distro*
  declare -gA args distro
  distro[pacman]='pacman'
  [[ -f $bin/yay ]] && distro[pacman]='yay'

  # check if package manager exist
  pkgMgr="${distro[$1]:-$1}"
  [[ -f $bin/$pkgMgr ]]
} # pkg_mgr

# set our first arguments
case $1 in
  -a|install) a="$1" ;;
  -i|show) i="$1" ;;
  -l) l="$1" ;;
  -la) la="$1" ;;
  -s|search) s="$1" ;;
  -d|delete|rmv|remove|uninstall) d="$1" ;;
  -u|update) u="$1" ;;
esac

# set package manager arguments per our argumentss
if pkg_mgr pacman ; then
  args=( 
    [${a:-add}]='-S'
    [${i:-info}]='-Si --color=auto'
    [${l:-list}]='-Qe --color=auto'
    [${la:-list-all}]='-Q --color=auto'
    [${s:-look}]='-Ss --color=auto'
    [${d:-del}]='-Runss'
    [${u:-sync}]='-Syu'
  ) # args
elif pkg_mgr apt ; then
  args=(  
    [${a:-add}]='install'
    [${i:-info}]='show'
    [${l:-list}]='list --installed'
    [${la:-list-all}]='list'
    [${s:-look}]='search'
    [${d:-del}]='purge'
    [${u:-sync}]='update
      -y full-upgrade
      -y autoremove' # sync
  ) # args
elif pkg_mgr rpm ; then
  args=( 
    [${a:-add}]='-ih'
    [${i:-info}]='-qi'
    [${l:-list}]='-qa'
    [${s:-look}]='-q'
    [${d:-del}]='-eh'
    [${u:-sync}]='-Uh'
  )
elif pkg_mgr winget ; then
  args=( 
    [${a:-add}]='install'
    [${i:-info}]='show'
    [${l:-list}]='list --name'
    [${s:-look}]='search -q --name'
    [${d:-del}]='uninstall'
    [${u:-sync}]='upgrade --all'
  )
fi

# run each argument with package manager
while IFS=$'\n' read -r arg ; do
  $pkgMgr $arg ${@/$1}
done <<< ${args[${1:-sync}]}
