#!/bin/bash

pkg_mgr() {
  # set bin path
  bin='/usr/bin'
  [[ -d $bin ]] || {
    bin='C:/Program Files'
    [[ -d $bin ]] || bin='/data/data/com.termux/files/usr/bin'
  }

  # set package manager by *distro*
  declare -gA args distro
  distro[pacman]='pacman'
  [[ -f $bin/yay ]] && distro[pacman]='yay'

  # check if package manager exist
  pkgMgr="${distro[$1]:-$1}"
  [[ -f $bin/$pkgMgr ]]
} # pkg_mgr

# set our arguments
h='help'
a='add'
i='info'
l='list'
la='list-all'
s='look'
d='del'
u='sync'
case $1 in
  -\?|-h|--help) h="$1" ;;
  -a|install) a="$1" ;;
  -i|show) i="$1" ;;
  -l) l="$1" ;;
  -la) la="$1" ;;
  -s|search) s="$1" ;;
  -d|delete|rmv|remove|uninstall) d="$1" ;;
  -u|update) u="$1" ;;
esac

# set package manager arguments per our argumentss
if pkg_mgr pacman ; then
  args=( 
    [$h]='-h'
    [$a]='-S'
    [$i]='-Si --color=auto'
    [$l]='-Qe --color=auto'
    [$la]='-Q --color=auto'
    [$s]='-Ss --color=auto'
    [$d]='-Runss'
    [$u]='-Syu'
  ) # args
elif pkg_mgr apt ; then
  args=( 
    [$h]='-h'
    [$a]='install'
    [$i]='show'
    [$l]='list --installed'
    [$la]='list'
    [$s]='search'
    [$d]='purge'
    [$u]='update
      -y full-upgrade
      -y autoremove' # sync
  ) # args
elif pkg_mgr rpm ; then
  args=( 
    [$h]='--help'
    [$a]='-ih'
    [$i]='-qi'
    [$l]='-qa'
    [$s]='-q'
    [$d]='-eh'
    [$u]='-Uh'
  )
elif pkg_mgr winget ; then
  args=( 
    [$h]='-?'
    [$a]='install'
    [$i]='show'
    [$l]='list --name'
    [$s]='search -q --name'
    [$d]='uninstall'
    [$u]='upgrade --all'
  )
fi

# run each argument with package manager
while IFS=$'\n' read -r arg ; do
  $pkgMgr $arg ${@/$1}
done <<< ${args[${1:-sync}]}
