#!/bin/bash

. ./src/common.sh

trap 'exit' INT
trap deinit_term EXIT

if hash pacman; then
    . ./src/pacman.sh
elif hash apt; then
    . ./src/apt.sh
fi

opers=(
    'Info'
    'Query'
    'Install'
    'List Installed'
    'Delete'
)

init_term
_update
_draw "${opers[@]}"

for((;;)) {
    _sbar '[>] do'
    hover_interface opers

    [[ $REPLY =~ ^''$|^'[C'$|^[lLdD]$ ]]&& {
        case ${opers[cursor-LINES]} in
            "${opers[0]}") _info;;
            "${opers[1]}") _query;;
            "${opers[2]}") _install;;
            "${opers[3]}") list_installed;;
            "${opers[4]}") _delete;;
        esac
        
        _draw "${opers[@]}"
    }
}